login/urls.py
from django.urls import path
from .import views
app_name = 'login'
urlpatterns = [

   path("",views.home,name='home'),
   path("userlogin",views.login,name='userlogin'),
   path("manager_registration",views.register_manager,name='manager_register'),
   path("managerlogin",views.manager_login,name='managerlogin'),
   path("ownerlogin",views.owner_login,name='ownerlogin'),
   path("user_registration",views.register_user,name='user_register')
   
]

manager/urls.py
from django.urls import path
from .import views
app_name = 'manager'

urlpatterns = [

   path("",views.manager_home,name='manager_home'),
   path("addturf",views.add_turf,name='addturf'),
   path("viewturf",views.view_turf,name='viewturf'),
   path("viewbooking",views.bookings,name='viewbooking'),
   path("bookinghistory",views.booking_history,name='bookinghistory')
   
]

turfbooking/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('owner/', include('owner.urls')),
    path('manager/', include('manager.urls')),
    path('', include('login.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
   path("",views.user_home,name='userhome'),
   path("turfdetails",views.turf_view,name='turfview'),
   path("bookingdetails",views.booking_details,name='details'),
   path("turfbooking",views.turf_booking,name='booking'),
   path("bookinghistory",views.booking_history,name='history'),
   path("log_out",views.logout,name='log_out')
]

manager/views.py
from django.shortcuts import render
from django.http import HttpResponse

def manager_home(request):
    return render(request,'manager/manager_home.html')


def add_turf(request):
    return render(request,'manager/add_turf.html')


def view_turf(request):
    return render(request,'manager/view_turf.html')


def bookings(request):
    return render(request,'manager/manager_booking_details.html')



def booking_history(request):
    return render(request,'manager/booking_history.html')

manager/templates/manager/add_turf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/manager_home.css' %}">
</head>
<body>
        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo">LETS FOOTBALL</label>
          <ul>
            <li><a class="active" href="{% url 'manager:manager_home' %}">Home</a></li>
            <li><a href="{% url 'manager:addturf' %}">ADD TURF</a></li>
            <li><a href="{% url 'manager:viewturf' %}">VIEW TURFS</a></li>
            <li><a href="{% url 'manager:viewbooking' %}">VIEW BOOKINGS</a></li>
            <!-- <li><a href="{% url 'manager:bookinghistory' %}">BOOKING HISTORY</a></li> -->
            <li><a href="{% url 'login:managerlogin' %}">LOGOUT</a></li>
          </ul>
        </nav>
        <section>
            <section>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div align="center">
                        <div class="addproduct">
                            <h1>ADD TURF</h1>
                            <div class="box1">
                                <label for="product_name">TURF NAME</label>
                                <input type="text" name="product_name" id="" placeholder="Turf name" required>
                            </div>
                            <div class="box1">
                                <label for="product_description">TURF DESCRIPTION</label>
                                <textarea name="product_description" id="" cols="22" rows="5" required></textarea>
                            </div>
                            <div class="box1">
                                <label for="rate">PRICE</label>
                                <input type="number" name="rate" id="" placeholder="Rates per hour" required>
                            </div>
                            <div class="box1">
                                <label for="opentime">OPENING TIME</label>
                                <input type="time" name="opentime" id="" placeholder="Opening Time" required>
                            </div>
                            <div class="box1">
                                <label for="closetime">CLOSING TIME</label>
                                <input type="time" name="closetime" id="" placeholder="Closing Time" required>
                            </div>
                            <div class="box1">
                                <label for="turfimage">IMAGE</label>
                                <input type="file" name="turfimage" id="" placeholder="product image" required>
                            </div> 
                        </div>
                        <button type="submit" class="btn btn-info">ADD</button>
                        {{msg}}
                
                    </div>
                    </form>

            </section>
            
        </section> 
        

        {% block content %}



        {% endblock %}
</body>
</html>

manager/templates/manager/booking_history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/manager_home.css' %}">
</head>
<body>
        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo">LETS FOOTBALL</label>
          <ul>
            <li><a class="active" href="{% url 'manager:manager_home' %}">Home</a></li>
            <li><a href="{% url 'manager:addturf' %}">ADD TURF</a></li>
            <li><a href="{% url 'manager:viewturf' %}">VIEW TURFS</a></li>
            <li><a href="{% url 'manager:viewbooking' %}">VIEW BOOKINGS</a></li>
            <!-- <li><a href="{% url 'manager:bookinghistory' %}">BOOKING HISTORY</a></li> -->
            <li><a href="{% url 'login:managerlogin' %}">LOGOUT</a></li>

          </ul>
        </nav>
        <section></section> 
        
</body>
</html>

manager/templates/manager/manager_booking_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/manager_home.css' %}">
</head>
<body>
        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo">LETS FOOTBALL</label>
          <ul>
            <li><a class="active" href="{% url 'manager:manager_home' %}">Home</a></li>
            <li><a href="{% url 'manager:addturf' %}">ADD TURF</a></li>
            <li><a href="{% url 'manager:viewturf' %}">VIEW TURFS</a></li>
            <li><a href="{% url 'manager:viewbooking' %}">VIEW BOOKINGS</a></li>
            <!-- <li><a href="{% url 'manager:bookinghistory' %}">BOOKING HISTORY</a></li> -->
            <li><a href="{% url 'login:managerlogin' %}">LOGOUT</a></li>

          </ul>
        </nav>
        <section></section> 
        
</body>
</html>

manager/templates/manager/manager_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/manager_home.css' %}">
</head>
<body>
        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo">LETS FOOTBALL</label>
          <ul>
            <li><a class="active" href="{% url 'manager:manager_home' %}">Home</a></li>
            <li><a href="{% url 'manager:addturf' %}">ADD TURF</a></li>
            <li><a href="{% url 'manager:viewturf' %}">VIEW TURFS</a></li>
            <li><a href="{% url 'manager:viewbooking' %}">VIEW BOOKINGS</a></li>
            <!-- <li><a href="{% url 'manager:bookinghistory' %}">BOOKING HISTORY</a></li> -->
            <li><a href="{% url 'login:managerlogin' %}">LOGOUT</a></li>

          </ul>
        </nav>
        <section></section> 
       
</body>
</html>

manager/templates/manager/managerhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome manager</h1>
</body>
</html>

manager/templates/manager/view_turf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/manager_home.css' %}">
</head>
<body>
        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo">LETS FOOTBALL</label>
          <ul>
            <li><a class="active" href="{% url 'manager:manager_home' %}">Home</a></li>
            <li><a href="{% url 'manager:addturf' %}">ADD TURF</a></li>
            <li><a href="{% url 'manager:viewturf' %}">VIEW TURFS</a></li>
            <li><a href="{% url 'manager:viewbooking' %}">VIEW BOOKINGS</a></li>
            <!-- <li><a href="{% url 'manager:bookinghistory' %}">BOOKING HISTORY</a></li> -->
            <li><a href="{% url 'login:managerlogin' %}">LOGOUT</a></li>

          </ul>
        </nav>
        <section></section> 
      
</body>
</html>