login/urls.py
from django.urls import path
from .import views
app_name = 'login'
urlpatterns = [

   path("",views.home,name='home'),
   path("userlogin",views.login,name='userlogin'),
   path("manager_registration",views.register_manager,name='manager_register'),
   path("managerlogin",views.manager_login,name='managerlogin'),
   path("ownerlogin",views.owner_login,name='ownerlogin'),
   path("user_registration",views.register_user,name='user_register')
   
]

owner/urls.py
from django.urls import path
from .import views
app_name = 'owner'

urlpatterns = [
   path("owner_home",views.owner_home,name='owner_home'),
   path("managerdetails",views.manager_details,name='details'),
   path("managerapproval",views.manager_approval,name='approvals'),
   path("userdetails",views.user_details,name='userdetails'),
   # path("users",views.user_available,name='users'),
   path("deletemanager",views.delete_manager,name='deletemanager'),
   path("managerapprovals",views.manager_approvals,name='managerapprovals'),
   path("log_out",views.logout,name='log_out'),
   path("loadmanager",views.load_manager,name='loadmanager'),
   path("availableuser",views.user_available,name='availableuser'),
   path("approvedmanager",views.approved_manager,name='approvedmanager'),

]

turfbooking/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('owner/', include('owner.urls')),
    path('manager/', include('manager.urls')),
    path('', include('login.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
   path("",views.user_home,name='userhome'),
   path("turfdetails",views.turf_view,name='turfview'),
   path("bookingdetails",views.booking_details,name='details'),
   path("turfbooking",views.turf_booking,name='booking'),
   path("bookinghistory",views.booking_history,name='history'),
   path("log_out",views.logout,name='log_out')
]

owner/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from login.models import Users
from login.models import Turfmanager
from .models import *

def owner_home(request):
    return render(request,'owner/owner_home.html')


def manager_details(request):
    return render(request,'owner/manager_details.html')


def manager_approval(request):
    return render(request,'owner/manager_approval.html')

def user_details(request):
    return render(request,'owner/user_details.html')

def logout(request):
    # del request.session['user_id']
    # request.session.flush()
    return redirect('login:ownerlogin')

def load_manager(request):
    managers = Turfmanager.objects.filter(manager_status='pending')
    data = [{'id': manager.id, 'name': manager.manager_name, 'email': manager.manager_email,
             'address': manager.manager_address, 'phone': manager.manager_phone,'image': manager.manager_image.url} for manager in managers]
             
    print(data)
    return JsonResponse({'data': data})

def delete_manager(request):
    id = request.POST['id']
    manager = Turfmanager.objects.get(id=id)
    manager.delete()
    return JsonResponse({'status': 'manager deleted'})

def manager_approvals(request):
    id = request.POST['id']
    manager = Turfmanager.objects.get(id=id)
    manager.manager_status='approved'
    manager.save()
    send_mail(
    'Approved',
    'Hi we are pleased to inform you that user request has been approved.',
    'sanjayproject222@gmail.com',
    [manager.manager_email],
    fail_silently=False,
)
    return JsonResponse({'status': 'manager approved'})


def user_available(request):
    users = Users.objects.all()
    data = [{'id': user.id, 'name': user.user_name, 'email': user.user_email,
              'phone': user.user_phone} for user in users]
             
    print(data)
    return JsonResponse({'data': data})

def approved_manager(request):
    managers = Turfmanager.objects.filter(manager_status='approved')
    data = [{'id': manager.id, 'name': manager.manager_name, 'email': manager.manager_email,
             'address': manager.manager_address, 'phone': manager.manager_phone, 'image': manager.manager_image.url} for manager in managers]
             
    print(data)
    return JsonResponse({'data': data})

owner/templates/owner/manager_approval.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/owner_home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    img{
        width: 150px;
        height: 100px;
    }
</style>
<body onload="load_Manager()">
    <div>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
              <i class="fas fa-bars"></i>
            </label>
            <label class="logo">Lets Football</label>
            <ul>
              <li><a class="active" href="{% url 'owner:owner_home' %}">Home</a></li>
              <li><a href="{% url 'owner:approvals' %}">Approvals</a></li>
              <li><a href="{% url 'owner:details' %}">Managers</a></li>
              <li><a href="{% url 'owner:userdetails' %}">Users</a></li>
              <li><a href="{% url 'login:ownerlogin' %}">Logout</a></li>
            </ul>
          </nav>
    </div>
    <div align="center">
        <form action="" method="POST">
            {% csrf_token %}
            <table border="2px" cellspacing="50px" cellpadding="50px" align="center" id="manager_table">
                <tr>
                  <th>ID</th>
                  <th>NAME</th>
                  <th>ADDRESS</th>
                  <th>EMAIL</th>
                  <th>PHONE NO</th>
                  <th>IMAGE</th>    
                  <th>ACTION</th>
                </tr>
            </table>
        </form>
     </div>
 
    
    <script>
        function load_Manager() {
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
                }
            })
            $.ajax({
                url: 'http://127.0.0.1:8000/owner/loadmanager',
                method: 'POST',
                success: function (response) {
                    console.log(response.data.length)
                    data = response.data
                    for (var i = 0; i < data.length; i++) {

                        $('#manager_table').append("<tr class='tr' id=row" + data[i].id + "><td class='row-data' id=std" + data[i].id + ">" + data[i].id + "</td><td class='row-data'>"
                            + data[i].name + "</td><td class='row-data'>" + data[i].address + "</td><td class='row-data'>" + data[i].email + "</td><td class='row-data'>" + data[i].phone + "</td><td class='row-data'><img src=" + data[i].image +
                            "></td><td><button type='button' class='btn btn-primary' data-toggle='modal' data-target='#updateModal' onclick=approvemanager(" + data[i].id + ")>approve</button></td><td><button type='button' class='btn btn-danger' onclick=deletemanager(" + data[i].id + ")>Delete</button> </td></tr>")
                    }

                }

            })
        }
        function deletemanager(id) {
            console.log(id)
            $.ajax({
                url: 'http://127.0.0.1:8000/owner/deletemanager',
                method: 'POST',
                data: {

                    'id': id,

                },
                success: function (response) {
                    console.log(response.status)
                    data = response.data
                   $('.tr').empty()
                    load_Manager()

                }
            })
        }
        function approvemanager(id) {
            console.log(id)
            $.ajax({
                url: 'http://127.0.0.1:8000/owner/managerapprovals',
                method: 'POST',
                data: {

                    'id': id,

                },
                success: function (response) {
                    console.log(response.status)
                    data = response.data
                    $('.tr').empty()
                    load_Manager()

                }
            })
        }
    </script>
</body>
</html>

owner/templates/owner/manager_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/owner_home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    img{
        width: 150px;
        height: 100px;
    }
</style>
<body onload="approved_manager()">
    <div>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
              <i class="fas fa-bars"></i>
            </label>
            <label class="logo">Lets Football</label>
            <ul>
              <li><a class="active" href="{% url 'owner:owner_home' %}">Home</a></li>
              <li><a href="{% url 'owner:approvals' %}">Approvals</a></li>
              <li><a href="{% url 'owner:details' %}">Managers</a></li>
              <li><a href="{% url 'owner:userdetails' %}">Users</a></li>
              <li><a href="{% url 'login:ownerlogin' %}">Logout</a></li>
            </ul>
         
          </nav>
    </div>
    <div align="center">
        <form action="" method="POST">
            {% csrf_token %}
            <table border="2px" cellspacing="25px" cellpadding="25px" align="center" id="approved_manager" align="center">
                <tr>
                  <th>ID</th>
                  <th>NAME</th>
                  <th>ADDRESS</th>
                  <th>EMAIL</th>
                  <th>PHONE NO</th>
                  <th>IMAGE</th>    
                </tr>
            </table>
        </form>

    </div>
    
    <script>
        function approved_manager() {
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
                }
            })
            $.ajax({
                url: 'http://127.0.0.1:8000/owner/approvedmanager',
                method: 'POST',
                success: function (response) {
                    console.log(response.data.length)
                    data = response.data
                    for (var i = 0; i < data.length; i++) {
  
                        $('#approved_manager').append("<tr class='tr' id=row" + data[i].id + ">" +"</td><td class='row-data'>"
                            + data[i].name + "</td><td class='row-data'>" + data[i].address + "</td><td class='row-data'>" + data[i].email + "</td><td class='row-data'>" + data[i].phone + "</td><td class='row-data'> <img src=" + data[i].image + 
                            "></td>")
                    }
  
                }
  
            })
        }
    </script>
</body>
</html>

owner/templates/owner/owner_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/owner_home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    img{
        width: 150px;
        height: 100px;
    }
</style>
<body onload="load_Seller()">
    <div>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
              <i class="fas fa-bars"></i>
            </label>
            <label class="logo">Lets Football</label>
            <ul>
              <li><a class="active" href="{% url 'owner:owner_home' %}">Home</a></li>
              <li><a href="{% url 'owner:approvals' %}">Approvals</a></li>
              <li><a href="{% url 'owner:details' %}">Managers</a></li>
              <li><a href="{% url 'owner:userdetails' %}">Users</a></li>
              <li><a href="{% url 'login:ownerlogin' %}">Logout</a></li>
            </ul>
         
          </nav>
    </div> 
</body>
</html>

owner/templates/owner/ownerhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="">Approvals</a>
    <a href="">User details</a>
    <a href="">Manager Details</a>
</body>
</html>

owner/templates/owner/user_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/owner_home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    img{
        width: 150px;
        height: 100px;
    }
</style>
<body onload="available_user()">
    <div>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
              <i class="fas fa-bars"></i>
            </label>
            <label class="logo">Lets Football</label>
            <ul>
              <li><a class="active" href="{% url 'owner:owner_home' %}">Home</a></li>
              <li><a href="{% url 'owner:approvals' %}">Approvals</a></li>
              <li><a href="{% url 'owner:details' %}">Managers</a></li>
              <li><a href="{% url 'owner:userdetails' %}">Users</a></li>
              <li><a href="{% url 'login:ownerlogin' %}">Logout</a></li>
            </ul>
         
          </nav>
    </div>
    <div align="center">
        <form action="" method="POST">
            {% csrf_token %}
            <table border="2px" cellspacing="25px" cellpadding="25px" align="center" id="user_table" align="center">
                <tr>
                  <th>ID</th>
                  <th>NAME</th>
                  <th>EMAIL</th>
                  <th>PHONE NO</th>   
                </tr>
            </table>
        </form>

    </div>
    
    <script>
        function available_user() {
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
                }
            })
            $.ajax({
                url: 'http://127.0.0.1:8000/owner/availableuser',
                method: 'POST',
                success: function (response) {
                    console.log(response.data.length)
                    data = response.data
                    for (var i = 0; i < data.length; i++) {
  
                        $('#user_table').append("<tr class='tr' id=row" + data[i].id + ">" +"</td><td class='row-data'>"
                            + data[i].name + "</td><td class='row-data'>" + data[i].email + "</td><td class='row-data'>" + data[i].phone + "</td>")
                    }
  
                }
  
            })
        }
    </script>
</body>
</html>