login/urls.py
from django.urls import path
from .import views
app_name = 'login'
urlpatterns = [

   path("",views.home,name='home'),
   path("userlogin",views.login,name='userlogin'),
   path("manager_registration",views.register_manager,name='manager_register'),
   path("managerlogin",views.manager_login,name='managerlogin'),
   path("ownerlogin",views.owner_login,name='ownerlogin'),
   path("user_registration",views.register_user,name='user_register')
   
]

turfbooking/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('owner/', include('owner.urls')),
    path('manager/', include('manager.urls')),
    path('', include('login.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
   path("",views.user_home,name='userhome'),
   path("turfdetails",views.turf_view,name='turfview'),
   path("bookingdetails",views.booking_details,name='details'),
   path("turfbooking",views.turf_booking,name='booking'),
   path("bookinghistory",views.booking_history,name='history'),
   path("log_out",views.logout,name='log_out')
]

login/models.py
from django.db import models
from distutils.command.upload import upload
from email.policy import default
from unittest.util import _MAX_LENGTH

class Admin(models.Model):
    admin_id = models.IntegerField()
    admin_password = models.CharField(max_length=20)


class User(models.Model):
    user_email = models.CharField(max_length=50)
    user_password = models.CharField(max_length=20)
    user_phone = models.BigIntegerField()
    
class Users(models.Model):
    user_name = models.CharField(max_length=50)
    user_email = models.CharField(max_length=50)
    user_password = models.CharField(max_length=20)
    user_phone = models.BigIntegerField()

class Managers(models.Model):
    manager_name = models.CharField(max_length=50)
    manager_address = models.CharField(max_length=100)
    manager_email = models.CharField(max_length=50)
    manager_password = models.CharField(max_length=20)
    manager_image = models.ImageField(upload_to='manager/')
    manager_phone = models.BigIntegerField()
    manager_status = models.CharField(max_length=40,default='pending')

class Turfmanager(models.Model):
    manager_name = models.CharField(max_length=50)
    manager_address = models.CharField(max_length=100)
    manager_email = models.CharField(max_length=50)
    manager_password = models.CharField(max_length=20)
    manager_image = models.ImageField(upload_to='manager/')
    manager_phone = models.BigIntegerField()
    manager_status = models.CharField(max_length=40,default='pending')

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from urllib.request import Request
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse
from .models import *

def home(request):
    return render(request,'login/common_home.html')


def login(request):
    msg=''
    if request.method == 'POST':
        u_name = request.POST['email']
        u_pass = request.POST['password']
        data_exits=User.objects.filter(user_email=u_name,user_password=u_pass).exists()
        if data_exits:
            user_data=Users.objects.get(user_email=u_name,user_password=u_pass)
            request.session['user_id']=user_data.id
            request.session['user_name']=user_data.user_name
            msg='logged in successfully'
            return render(request,'login/common_home.html',{'message':msg})
        else:
            msg='incorrect username or password'

    return render(request,'login/log_in.html',{'message':msg})


def manager_login(request):
    msg=''
    if request.method == 'POST':
        m_name = request.POST['username']
        m_pass = request.POST['password']
        manager_exists=Turfmanager.objects.filter(manager_email=m_name,manager_password=m_pass).exists()
        if manager_exists:
            manager_data=Turfmanager.objects.get(manager_email=m_name,manager_password=m_pass)
            if manager_data.manager_status== 'approved':
                request.session['manager_id']=manager_data.id
                return redirect('manager:manager_home')
            else:
                msg = 'Not approved by admin'
            
        else:
            msg='incorrect username or password'

    return render(request,'login/manager_login.html',{'message':msg})


def register_manager(request):

    msg=''
    if request.method == 'POST':
        m_name = request.POST['name']
        m_eml = request.POST['email']
        m_phone = request.POST['number']
        m_passw = request.POST['password']
        m_address = request.POST['address']
        m_file = request.FILES['picture']
        
       
        manager_exists=Turfmanager.objects.filter(manager_email=m_eml).exists()
        if not manager_exists:

             obj = Turfmanager(manager_name=m_name,manager_email=m_eml,manager_password=m_passw,manager_phone=m_phone,manager_address=m_address,manager_image=m_file)
             obj.save()
             msg='Registration successfull'

        
        else:
            msg='email already exist'

    return render(request,'login/manager_registration.html',{'message':msg})


def register_user(request):

    msg=''
    if request.method == 'POST':
        u_name = request.POST['name']
        u_eml = request.POST['email']
        U_passw = request.POST['password']
        u_phone = request.POST['telephone']
       
        user_exists=Users.objects.filter(user_email=u_eml).exists()
        if not user_exists:

             obj = Users(user_name=u_name,user_email=u_eml,user_password=U_passw,user_phone=u_phone)
             obj.save()
             msg='Registration successfull'

        
        else:
            msg='email already exist'

    return render(request,'login/user_registration.html',{'message':msg})


def owner_login(request):
    msg=''
    if request.method == 'POST':
        a_name = request.POST['username']
        a_pass = request.POST['password']
        data_exits=Admin.objects.filter(admin_id=a_name,admin_password=a_pass).exists()
        if data_exits:
            admin_data=Admin.objects.get(admin_id=a_name,admin_password=a_pass)
            request.session['admin_id']=admin_data.id
            return redirect('owner:owner_home')
        else:
            msg='incorrect username or password'
    return render(request,'login/owner_login.html',{'message':msg})

login/templates/login/common_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</head>
<body style="background-color:rgb(230, 217, 217)">
    <header class="header header-fixheight">
        <nav>
            <ul>
              <li class="logo">LETS FOOTBALL</li>
              <li class="btn"><span class="fas fa-bars"></span></li>
              <div class="items">
                <li><a href="{% url 'login:home' %}">HOME</a></li>
                <li><a href="#turf">TURFS</a></li>
                <li><a href="#about">ABOUT US</a></li>
                {% if not 'user_id' in request.session %}
                <li><a href="{% url 'login:userlogin' %}">LOGIN</a></li>
                {% else %}
                <li><a href="{% url 'user:log_out' %}">LOGOUT</a>
                {% endif %}
              </div>
              <li class="search-icon">
                <input type="search" placeholder="Search">
                <label class="icon">
                  <span class="fas fa-search"></span>
                </label>
              </li>
            </ul>
          </nav>
        <!-- <div class="container">
            <div class="header__inner">
                <div class="header-logo"><a href="home.html"><img src="assets/img/logo_white.png" alt=""/></a></div>
                <nav class="raising-nav">
                    <ul class="raising-menu">
                        <li class="current"><a href="#id1">Home</a>
                        </li>
                        <li><a href="{% url 'login:userlogin' %}">LOGIN</a>
                        </li>
                        <li><a href="#turf">TURFS</a>
                        </li>
                        <li><a href="#about">ABOUT US</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div> -->
    </header>
    <div class="container-fluid p-0 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div id="header-carousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="w-100" src="{% static 'images/t4.jpg' %}" alt="Image" height="800px">
                    <div class="carousel-caption">
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="{% static 'images/t3.jpg' %} " alt="Image" height="800px">
                    <div class="carousel-caption">
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <section class="section" id="turf">
        <div class="container-xxl py-5">
            <div class="container">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-4">
                            <div class="col-xl-3 col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="product-item">
                                    <div class="position-relative bg-light overflow-hidden">
                                        <img class="img-fluid w-100" src="{% static 'images/fusion sport.jpg' %}" alt="" width="100px" height="400">
                                    </div>
                                    <div class="text-center p-4">
                                        <a class="d-block h5 mb-2" href="">Fusion sport footballturf</a>
                                        <span class="text-primary me-1"></span>
                                    </div>
                                    <div class="d-flex border-top">
                                        <small class="w-50 text-center border-end py-2">
                                            <a class="text-body" href=""><i class="fa fa-eye text-primary me-2"></i>View detail</a>
                                        </small>
                                        <small class="w-50 text-center py-2">
                                            <a class="text-body" href=""><i class="fa fa-shopping-bag text-primary me-2"></i>Book now</a>
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<div>
    <!-- Footer -->
    <footer
            class="text-center text-lg-start text-white"
            style="background-color: #45526e"
            >
     
      <div class="container p-4 pb-0">
       
        <section class="" id="about">
        
          <div class="row">
            
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                BAABTRA
              </h6>
              <p>
                5th Floor, CAFIT Square, Hilite Buisness Park, Thondayad Bye-Pass, Hilite City, Poovangal, Kozhikode, Kerala 673016
              </p>
            </div>
           
  
            <hr class="w-100 clearfix d-md-none" />
  
         
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">POLICY</h6>
              <p>
                <a class="text-white">Return Policy</a>
              </p>
              <p>
                <a class="text-white">Terms of use</a>
              </p>
              <p>
                <a class="text-white">Security</a>
              </p>
              <p>
                <a class="text-white">Privacy</a>
              </p>
            </div>
           
  
            <hr class="w-100 clearfix d-md-none" />
  
           
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                ABOUT
              </h6>
              <p>
                <a class="text-white">About Us</a>
              </p>
              <p>
                <a class="text-white">New updates</a>
              </p>
              <p>
                <a class="text-white">Help</a>
              </p>
            </div>
  
           
            <hr class="w-100 clearfix d-md-none" />
  
            
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
              <p><i class="fas fa-home mr-3"></i> Malakkal House</p>
              <p><i class="fas fa-envelope mr-3"></i> turfbookings@gmail.com</p>
              <p><i class="fas fa-phone mr-3"></i> + 91 7736104298</p>
              <p><i class="fas fa-print mr-3"></i> + 91 8136932034</p>
            </div>
            
          </div>
          
        </section>
        
  
        <hr class="my-3">
  
        
        <section class="p-3 pt-0">
          <div class="row d-flex align-items-center">
           
            <div class="col-md-7 col-lg-8 text-center text-md-start">
             
              <div class  align="center">
                © 2022 Copyright:
                <a class="text-white" href=""
                   >Visit again</a
                  >
              </div>
              <!-- Copyright -->
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
              <!-- Facebook -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="fab fa-facebook-f"></i
                ></a>
  
              <!-- Twitter -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="fab fa-twitter"></i
                ></a>
  
              <!-- Google -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="fab fa-google"></i
                ></a>
  
              <!-- Instagram -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="fab fa-instagram"></i
                ></a>
            </div>
            <!-- Grid column -->
          </div>
        </section>
        <!-- Section: Copyright -->
      </div>
      <!-- Grid container -->
    </footer>
    <!-- Footer -->
  </div>
  <!-- End of .container -->
  
</div>
</body>
</html>

login/templates/login/log_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>User Login</title>
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<script src=""></script>
	<script src="{% static 'js/valid.js' %}"></script>
	<style>
		* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial;
  font-size: 17px;
}

#myVideo {
  position: absolute;
  right: 0;
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
}

.content {
  position: fixed;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #f1f1f1;
  width: 100%;
  padding: 20px;
}

	</style>
</head>
<body>
	<video autoplay muted loop id="myVideo">
		<source src="{% static 'images/f2.mp4' %}" type="video/mp4">
	</video>
	<div class="container">
		<h1 class="label">User Login</h1>
		<form class="login_form" action="" method="POST" name="form" onsubmit="return validated()">
			{% csrf_token %}
			{{message}} 
			<div class="font">Email</div>
			<input autocomplete="off" type="text" name="email">
			<div id="email_error">Please Enter Your Username or Email</div>
			<div class="font font2">Password</div>
			<input type="password" name="password">
			<div id="pass_error">Please Enter your Password</div>
			<button type="submit">Login</button>
		</form>
		<div id="create-account-wrap" align="center">
			<p>Not a member? <a href="{% url 'login:user_register' %}">Create Account</a><p>
		</div>
	</div>	
	<script>
		var email = document.forms['form']['email'];
		var password = document.forms['form']['password'];

		var email_error = document.getElementById('email_error');
		var pass_error = document.getElementById('pass_error');

		email.addEventListener('textInput', email_Verify);
		password.addEventListener('textInput', pass_Verify);

		function validated(){
			if (email.value.length < 9) {
				email.style.border = "1px solid red";
				email_error.style.display = "block";
				email.focus();
				return false;
			}
			if (password.value.length < 6) {
				password.style.border = "1px solid red";
				pass_error.style.display = "block";
				password.focus();
				return false;
			}

		}
		function email_Verify(){
			if (email.value.length >= 8) {
				email.style.border = "1px solid silver";
				email_error.style.display = "none";
				return true;
			}
		}
		function pass_Verify(){
			if (password.value.length >= 5) {
				password.style.border = "1px solid silver";
				pass_error.style.display = "none";
				return true;
			}
		}
	</script>	
	
</body>
</html>

login/templates/login/manager_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Manager Login</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/manager.css' %}">
</head>
<body>

<div id="login-form-wrap">
  <h2>Login</h2>
  <form id="login-form" action="" method="POST">
    {% csrf_token %}
    
    <p>
    <input type="email" id="username" name="username" placeholder="Username" required><i class="validation"><span></span><span></span></i>
    </p>
    <p>
    <input type="password" id="password" name="password" placeholder="Password" required><i class="validation"><span></span><span></span></i>
    </p>
    <p>
    <input type="submit" id="login" value="Login">
    </p>
    {{message}}
  </form>
  <div id="create-account-wrap">
    <p>Not a member? <a href="{% url 'login:manager_register' %}">Create Account</a><p></p>
  </div>
</div>

  
</body>
</html>

login/templates/login/manager_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Registration </title>
    <link rel="stylesheet" href="{% static 'css/manager_register.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Registration</div>
    <div class="content">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{message}} 
        <div class="user-details">
          <div class="input-box">
            <span class="details">Name</span>
            <input type="text" placeholder="Enter your name" required name="name">
          </div>
          <!-- <div class="input-box">
            <span class="details">Username</span>
            <input type="text" placeholder="Enter your username" required>
          </div> -->
          <div class="input-box">
            <span class="details">Email</span>
            <input type="email" placeholder="Enter your email" required name="email">
          </div>
          <div class="input-box">
            <span class="details">Phone Number</span>
            <input type="tel" placeholder="Enter your number" required name="number" pattern="[6789][0-9]{9}">
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" placeholder="Enter your password" required name="password">
          </div>
          <div class="input-box">
            <span class="details">Address</span>
            <textarea  class="" name="address" id="" cols="98" rows="10" required placeholder="Enter Address"></textarea>
          </div>
          <div align="center">
            <span class="details">Upload picture</span>
            <input type="file" placeholder="Files" required name="picture">
          </div>
        </div>
        <div class="button">
          <input type="submit" value="Register">
        </div>
        <div id="create-account-wrap" align="center">
          <p> <a href="{% url 'login:managerlogin' %}">Login</a><p>
        </div>
      </form>
    </div>
  </div>

</body>
</html>

login/templates/login/owner_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Admin login</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'css/owner.css' %}">
</head>
<body>

<div id="login-form-wrap">
  <h2>Login</h2>
  <form id="login-form" method="POST">
    {% csrf_token %}
    <p>
    <input type="number" id="username" name="username" placeholder="Username" required><i class="validation"><span></span><span></span></i>
    </p>
    <p>
    <input type="password" id="password" name="password" placeholder="Password" required><i class="validation"><span></span><span></span></i>
    </p>
    <p>
    <input type="submit" id="login" value="Login">
    </p>
    {{message}}
  </form>
  <div id="create-account-wrap">
 
  </div>
</div>

  
</body>
</html>

login/templates/login/user_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <link rel="stylesheet" href="{% static 'css/user_register.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
      		* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial;
  font-size: 17px;
}

#myVideo {
  position: absolute;
  right: 0;
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
}

.content {
  position: fixed;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #f1f1f1;
  width: 100%;
  padding: 20px;
}
    </style>
</head>
<body>
  <video autoplay muted loop id="myVideo">
		<source src="{% static 'images/f2.mp4' %}" type="video/mp4">
	</video>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form_wrapper">
        <div class="form_container">
          <div class="title_container">
            <h2>Lets Create An Account</h2>
          </div>
          <div class="row clearfix">
            <div class="">
              <form>
                {{message}} 
                <div class="input_field"> <span><i aria-hidden="true" class="fa fa-profile"></i></span>
                  <input type="text" name="name" placeholder="Name" required />
                </div>
                <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
                  <input type="email" name="email" placeholder="Email" required />
                </div>
                <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
                  <input type="password" name="password" placeholder="Password" required />
                </div>
                <div class="input_field"> <span><i aria-hidden="true" class="fa fa-phone"></i></span>
                  <input type="tel" name="telephone" placeholder="phone no" required pattern="[6789][0-9]{9}" />
                  
                </div>
                <small>Mobile no Format: 123-456-7890</small>
                <!-- <div class="input_field"> <span><i aria-hidden="true" class=""></i></span>
                  <input type="file" name="telephone" placeholder="Upload Profile pic" required />
                </div> -->
                <div class="input_field checkbox_option">
                      <input type="checkbox" id="cb1">
                      <label for="cb1">I agree with terms and conditions</label>
                </div>
                <input class="button" type="submit" value="REGISTER" />
                <div id="create-account-wrap" align="center">
                  <p> <a href="{% url 'login:userlogin' %}">Already Have an Account</a><p>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </form>
</body>
</html>