login/urls.py
from django.urls import path
from .import views
app_name = 'login'
urlpatterns = [

   path("",views.home,name='home'),
   path("userlogin",views.login,name='userlogin'),
   path("manager_registration",views.register_manager,name='manager_register'),
   path("managerlogin",views.manager_login,name='managerlogin'),
   path("ownerlogin",views.owner_login,name='ownerlogin'),
   path("user_registration",views.register_user,name='user_register')
   
]

turfbooking/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('owner/', include('owner.urls')),
    path('manager/', include('manager.urls')),
    path('', include('login.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
   path("",views.user_home,name='userhome'),
   path("turfdetails",views.turf_view,name='turfview'),
   path("bookingdetails",views.booking_details,name='details'),
   path("turfbooking",views.turf_booking,name='booking'),
   path("bookinghistory",views.booking_history,name='history'),
   path("log_out",views.logout,name='log_out')
]

user/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponse
from urllib.request import Request
from django.shortcuts import redirect, render
from .models import *
from login.models import Users
# Create your views here.
def user_home(request):
    user_data = User.objects.get(id = request.session['user_id'])
    
    return render(request,'user/user_home.html',{'user' : user_data})


def turf_view(request):
    return render(request,'user/user_turf_view.html')


def booking_details(request):
    return render(request,'user/booking_details.html')


def turf_booking(request):
    return render(request,'user/book_turf.html')


def booking_history(request):
    return render(request,'user/booking_history.html')


def logout(request):
    del request.session['user_id']
    request.session.flush()
    return redirect('login:home')

user/templates/user/book_turf.html
{% extends 'user/user_home.html' %}


{% block content %}




{% endblock %}

user/templates/user/booking_details.html
{% extends 'user/user_home.html' %}


{% block content %}




{% endblock %}

user/templates/user/user_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'css/user_home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</head>
<body>
  <header class="header header-fixheight">
    <nav>
        <ul>
          <li class="logo">LETS FOOTBALL</li>
          <li class="btn"><span class="fas fa-bars"></span></li>
          <div class="items">
            <li><a href="{% url 'user:userhome' %}">HOME</a></li>
            <li><a href="{% url 'user:details' %}">BOOKING DETAILS</a></li>
            <li><a href="{% url 'user:booking' %}">COMPLAINTS</a></li>
          </div>
          <li class="search-icon">
            <input type="search" placeholder="Search">
            <label class="icon">
              <span class="fas fa-search"></span>
            </label>
          </li>
        </ul>
      </nav>
    <!-- <div class="container">
        <div class="header__inner">
            <div class="header-logo"><a href="home.html"><img src="assets/img/logo_white.png" alt=""/></a></div>
            <nav class="raising-nav">
                <ul class="raising-menu">
                    <li class="current"><a href="#id1">Home</a>
                    </li>
                    <li><a href="{% url 'login:userlogin' %}">LOGIN</a>
                    </li>
                    <li><a href="#turf">TURFS</a>
                    </li>
                    <li><a href="#about">ABOUT US</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div> -->
</header>
{% block content %}



{% endblock %}
</body>
</html>

user/templates/user/userhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome</h1>
</body>
</html>